accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

event_platform/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('events/' , include('events.urls')),
    path('accounts/', include('accounts.urls')), 
    path('tickets/', include('tickets.urls')), 
    path('discounts/', include('discounts.urls')),
    path('', RedirectView.as_view(url='events/', permanent=False)),     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    
    path('', views.event_list, name='list'),
    
    path('<int:pk>/', views.event_detail, name='detail'),
    
    path('create/' , views.event_create , name='create'),
    
    path('<int:pk>/dashboard', views.event_dashboard, name='dashboard'),
    
    path('<int:pk>/update', views.event_update, name='update'),
    
    path('<int:pk>/delete', views.event_delete, name='delete'),
    
    path('my-events/', views.my_events, name='my_events'),
    
    
]  

tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'

urlpatterns = [

    path('purchase/<int:event_id>/', views.ticket_purchase, name='purchase'),
    path('my-tickets/', views.ticket_list, name='list'),

]

templates/inc/navbar.html
<div class="navbar">
    <div class="navbar-right">
        <a href="{% url 'events:list' %}">🏠 صفحه اصلی</a>
        
        {% if user.is_authenticated %}
            
            <a href="{% url 'tickets:list' %}" style="background-color: #ff9800; margin-left: 20px;">🎫 بلیط‌های من</a>

            {% if user.profile.user_type == 'ORGANIZER' %}

                 <a href="{% url 'events:my_events' %}" style="background-color: #6610f2; margin-left: 10px;">📂 رویدادهای من</a>

                <a href="{% url 'events:create' %}" style="background-color: #0056b3;">+ ایجاد رویداد</a>

            {% endif %}
        {% endif %}
    </div>

    <div class="navbar-left">
        {% if user.is_authenticated %}
            <span style="padding: 12px; color: #ccc;">👤 {{ user.username }}</span>
            <form action="{% url 'accounts:logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" style="background: none; border: none; color: #ff6b6b; cursor: pointer; padding: 0 15px;">خروج</button>
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}">ورود</a>
            <a href="{% url 'accounts:signup' %}">ثبت نام</a>
        {% endif %}
    </div>
</div>